<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/20 03:17:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=proyecto',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
